### ISSUE TITLE
密码明文泄露啦

### ISSUE THREAD

**Issue by zhujinle** [1595258509/fuck-WZU-SPOC#1]
### 明天就盗号（bushi）
---
想问下原理，是人肉生成的题库还是通过解析服务器返回的json得到答案？
我看了下，好像post骚操作一下就能够从json中解析到卷子的答案😂

**Comment by Murlors** [comment]
发现了，~~其实是之前commit忘记push了~~\
试卷暂存的时候会把答题情况post，然后再次进入试卷时会返回该题目的‘errorFlag’，然后就靠枚举一个一个）

**Comment by zhujinle** [comment]
哦哦这个思路可以
我想到的是去构造一个假的post，再在getExamPaper这个api里面获取到quizResponses里面的答案数据，然后去做选项匹配。
现在看来感觉枚举会方便很多，不同paperid的题目和选项是打乱的，匹配起来太麻烦
上学期是进入答题的时候直接提供quizResponses的，直接匹配一下选项id就能拿到满分。这学期改进了，没有结束作答不会提供这个值🤣虽然可以通过假post获取到答案，但是是打乱过的，匹配起来还要解析html的文本，太麻烦

---

现在是只有选择吗，判断是留空不做的吗？我看没有itt002的代码

**Comment by Murlors** [comment]
对的，之前在发现了quizResponses这个函数，在其他的一些题目中测试时OK，但是切换到学校里的题目就返回空了\
现在是只有单选多选，判断的话，暂时在学校里没有找到现有试卷里有判断题，所以先放着了 ~~开摆~~
